module.exports={
    title:"v1.1.3",
    desc:"2021.1.1",
    exampleList:[
        {
            title:"scrollLink",
            contentList:[
                "增加复选框配置项"
            ]
        },
        {
            title:"tongConsole",
            contentList:[
                "增加控制台组件tongConsole"
            ]
        },
        {
            title:"tongSearch",
            contentList:[
                "tongSearch增加config字段，提供自定义配置项",
                "增加text，selector，cascader增加配置项placeholder"
            ]
        },{
            title:"tongBreadDialog",
            contentList:[
                "点击x关闭弹框的回调, closeCallback"
            ]
        },{
            title:"tongTable",
            contentList:[
                "调整审批弹框出现条件为 !(undefined,true)",
                "增加操作前的图片配置-支持可使用字体图标和图片",
                "调整model配置项，增加显隐配置show",
                "增加多级表头配置",
                "tongTable增加复选禁用配置方法",
                "修复固定列阴影"
            ]
        },{
            title:"tongSelect",
            contentList:[
                "增加condition每次只打开一个同级树节点展开配置项",
                "下拉树增加父子级联配置项",
                "tongSelect收起下拉项的时候重置树的过滤"
            ]
        },{
            title:"tongTree",
            contentList:[
                "tongTree的过滤方法节流调整为防抖",
                "增加condition每次只打开一个同级树节点展开配置项",
                "tongTree 对非array类型value转string类型处理",
                "tongTree右击菜单展示位置调整"
            ]
        },{
            title:"图表组件模块",
            contentList:[
                "甘特图增加dataZoom用户配置项",
                "图表类增加监控重绘，点击方法回调",
                "调整line，pie，radar，scatter入参配置项"
            ]
        },{
            title:"JS",
            contentList:[
                "单位转换去掉空格",
                "单位转换小转大，若为整数则省略小数点",
                "补充会话储存类",
                "增加deepMergeObject",
                "usual调整",
                "补充转换单位的类"
            ]
        }
    ]
}