export default {
    action: "",
    name: "file",
    data: null,
    headers: null,
    accept: "",
    multiple: false,
    limit: null,
    fileList: [],
    showFileList: true,
    disabled: false,
    autoUpload: false,
    drag: false,
    listType: "text",

    // onChange() {console.log(arguments)},
    // onSuccess() {},
    // onError() {},
    // onRemove() {},
    tip: "",
}